Repository Fimento/api-documentation, pull requests merged in 2023-02, with the labels that each got.

#12 [4591] Add reminder endpoint
  specifications.yml
Labels: main, yellow

#13 Payment plan
  specifications.yml
Labels: main, yellow

#23 [2075] Return the credit limit already utilised by customer
  specifications.yml
Labels: yellow, epic/instalments

#14 [620] Add dunning to invoice schema
  specifications.yml
Labels: main, yellow

#20 [2638] Add pending interest to get order return
  specifications.yml
Labels: main, yellow

#17 [8751] Add reminder endpoint body
  specifications.yml
Labels: main, yellow

#25 [1510] Document pricing info
  specifications.yml
Labels: epic/instalments

#24 [1664] Return updated invoice in manual reminder endpoint
  specifications.yml
Labels: yellow, epic/instalments

#18 Credit notes
  specifications.yml
Labels: yellow, epic/instalments

#26 [4028] Add late fee type to reminder types
  specifications.yml
Labels: yellow, epic/instalments

#22 Add postman collection
  postman_collection.json
  specifications.yml
Labels: yellow, epic/instalments

#15 [Epic] Instalments
  postman_collection.json
  specifications.yml
Labels: main, yellow

#28 [4126] Complete information returned by endpoint
  specifications.yml
Labels: main, WIP, blue

#27 [4122] Rename create order endpoint pricing fields
  postman_collection.json
  specifications.yml
Labels: main, blue
