Repository Fimento/api-documentation, pull requests merged in 2023-01, with the labels that each got.

#3 [8579] Add elkjop documentation
  specifications.yml
Labels: main

#4 [8579] Finis elkjop doc
  .gitignore
  specifications.yml
Labels: main, WIP

#5 [8579] Finis elkjop doc
  specifications.yml
Labels: main

#6 [8579] Finis elkjop doc
  specifications.yml
Labels: main

#7 [8579] Fix missing currency
  specifications.yml
Labels: main

#10 [7972] Correctly show required fields
  specifications.yml
Labels: main, yellow

#9 Align documentation to code
  specifications.yml
Labels: main

#8 [2855] Show status in invoice
  specifications.yml
Labels: main, yellow

#11 [Fix] Remove lost letter
  specifications.yml
Labels: main, yellow
